#!/usr/bin/env python3
"""OKF v0.1 conformance validator for raaptech-brain.

Checks:
1. Every non-reserved .md file has parseable YAML frontmatter.
2. Every frontmatter block contains a non-empty `type` field.
3. index.md and log.md follow reserved-filename conventions.
4. Cross-links are checked for existence (warn only — broken links are OK per spec).
5. Catalogue consistency: every catalog.md line resolves to an existing
   file (+anchor); domain-file H2/H3 headings missing from the catalogue warn.

Usage: python scripts/okf-validate.py [--strict]
"""

import sys
import yaml
from pathlib import Path

# catalog.md is generated by scripts/brain.py (reindex/save) and carries no
# frontmatter by design — treat it as reserved alongside index.md/log.md.
RESERVED = {"index.md", "log.md", "catalog.md"}
BUNDLE_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = BUNDLE_ROOT / "catalog.md"

# Reuse brain.py's slug/heading/domain logic so the two tools can't disagree.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from brain import DOMAINS, SKIP_FILES, slugged_headings  # noqa: E402
from brain import parse_frontmatter as split_frontmatter  # noqa: E402


def parse_frontmatter(path: Path) -> dict | None:
    """Extract YAML frontmatter from a markdown file. Returns None if missing/malformed."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    try:
        return yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return None


def validate_bundle(strict: bool = False) -> tuple[list[str], list[str], list[str]]:
    """Validate the bundle. Returns (errors, warnings, info)."""
    errors: list[str] = []
    warnings: list[str] = []
    info: list[str] = []

    md_files = sorted(BUNDLE_ROOT.rglob("*.md"))
    concept_files = [f for f in md_files if f.name not in RESERVED]
    index_files = [f for f in md_files if f.name == "index.md"]
    log_files = [f for f in md_files if f.name == "log.md"]

    info.append(f"Found {len(md_files)} .md files ({len(concept_files)} concepts, {len(index_files)} indexes, {len(log_files)} logs)")

    # Check 1: Every concept has parseable frontmatter with non-empty type
    for f in concept_files:
        fm = parse_frontmatter(f)
        if fm is None:
            errors.append(f"  MISSING FRONTMATTER: {f.relative_to(BUNDLE_ROOT)}")
            continue
        if not fm.get("type"):
            errors.append(f"  MISSING TYPE: {f.relative_to(BUNDLE_ROOT)}")
        else:
            info.append(f"  OK: {f.relative_to(BUNDLE_ROOT)} (type={fm['type']})")

    # Check 2: index.md files should NOT have frontmatter (per spec §6)
    for f in index_files:
        fm = parse_frontmatter(f)
        if fm is not None:
            warnings.append(f"  INDEX HAS FRONTMATTER: {f.relative_to(BUNDLE_ROOT)} — spec §6 says index.md has no frontmatter (except bundle-root for okf_version)")

    # Check 3: log.md should follow date-grouped structure
    for f in log_files:
        text = f.read_text(encoding="utf-8")
        if "## 20" not in text:
            warnings.append(f"  LOG MISSING DATE HEADINGS: {f.relative_to(BUNDLE_ROOT)} — spec §7 recommends YYYY-MM-DD headings")

    # Check 4: Cross-links (warn only — spec says consumers MUST tolerate broken links)
    if strict:
        all_paths = {f.relative_to(BUNDLE_ROOT).as_posix() for f in md_files}
        for f in concept_files:
            text = f.read_text(encoding="utf-8")
            for line in text.splitlines():
                if "](" in line and ".md)" in line:
                    # Extract markdown links
                    import re
                    for match in re.finditer(r"\]\(([^)]+\.md)\)", line):
                        target = match.group(1)
                        if target.startswith("/"):
                            target = target.lstrip("/")
                        if target not in all_paths and not target.startswith("http"):
                            warnings.append(f"  BROKEN LINK in {f.relative_to(BUNDLE_ROOT)}: -> {target}")

    return errors, warnings, info


def validate_catalog() -> tuple[list[str], list[str], list[str]]:
    """Catalogue-consistency check (spec §catalog).

    Errors: catalog.md lines that do not resolve to an existing file, or whose
    anchor matches no heading in that file.
    Warnings: H2/H3 headings in domain files that are absent from the catalogue.
    """
    errors: list[str] = []
    warnings: list[str] = []
    info: list[str] = []

    if not CATALOG_PATH.exists():
        warnings.append("  CATALOG MISSING: catalog.md — run `python scripts/brain.py reindex`")
        return errors, warnings, info

    heading_slugs: dict[str, set[str]] = {}  # rel path -> heading anchor slugs

    def slugs_for(rel: str) -> set[str]:
        if rel not in heading_slugs:
            _, body = split_frontmatter((BUNDLE_ROOT / rel).read_text(encoding="utf-8"))
            heading_slugs[rel] = {s for *_, s in slugged_headings(body)}
        return heading_slugs[rel]

    refs: set[str] = set()
    n_lines = 0
    for lineno, raw in enumerate(CATALOG_PATH.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|", 2)]
        if len(parts) != 3 or not parts[0]:
            warnings.append(f"  CATALOG MALFORMED: catalog.md:{lineno}")
            continue
        n_lines += 1
        ref = parts[0]
        path, _, anchor = ref.partition("#")
        if not (BUNDLE_ROOT / path).is_file():
            errors.append(f"  CATALOG DANGLING FILE: catalog.md:{lineno} -> {path}")
            continue
        if anchor and anchor not in slugs_for(path):
            errors.append(f"  CATALOG DANGLING ANCHOR: catalog.md:{lineno} -> {ref}")
        refs.add(ref)

    uncatalogued = 0
    for domain in DOMAINS:
        ddir = BUNDLE_ROOT / domain
        if not ddir.is_dir():
            continue
        for md in sorted(ddir.rglob("*.md")):
            if md.name in SKIP_FILES:
                continue
            rel = md.relative_to(BUNDLE_ROOT).as_posix()
            _, body = split_frontmatter(md.read_text(encoding="utf-8"))
            for level, _heading, _, slug in slugged_headings(body):
                if level not in (2, 3) or not slug:
                    continue
                if f"{rel}#{slug}" not in refs:
                    warnings.append(f"  NOT CATALOGUED: {rel}#{slug}")
                    uncatalogued += 1

    info.append(f"Catalogue: {n_lines} lines checked, {len(errors)} unresolved, "
                f"{uncatalogued} uncatalogued headings")
    return errors, warnings, info


def main():
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    strict = "--strict" in sys.argv
    errors, warnings, info = validate_bundle(strict=strict)
    cat_errors, cat_warnings, cat_info = validate_catalog()
    errors += cat_errors
    warnings += cat_warnings
    info += cat_info

    print("=" * 60)
    print("OKF v0.1 Conformance Check")
    print("=" * 60)

    for line in info:
        print(line)

    if warnings:
        print(f"\n⚠ Warnings ({len(warnings)}):")
        for w in warnings:
            print(w)

    if errors:
        print(f"\n❌ Errors ({len(errors)}):")
        for e in errors:
            print(e)
        print(f"\nBundle is NOT conformant. Fix {len(errors)} error(s).")
        sys.exit(1)
    else:
        print(f"\n✅ Bundle is OKF v0.1 conformant ({len(concept_files := [f for f in BUNDLE_ROOT.rglob('*.md') if f.name not in RESERVED])} concepts, 0 errors)")
        if warnings:
            print(f"   ({len(warnings)} non-blocking warnings)")

    # Summary
    dirs_with_index = {f.parent for f in BUNDLE_ROOT.rglob("index.md")}
    dirs_with_md = {f.parent for f in BUNDLE_ROOT.rglob("*.md") if f.name not in RESERVED}
    missing_index = dirs_with_md - dirs_with_index
    if missing_index:
        print(f"\n📁 Directories missing index.md ({len(missing_index)}):")
        for d in sorted(missing_index):
            print(f"   {d.relative_to(BUNDLE_ROOT)}/")


if __name__ == "__main__":
    main()